packages = ["sqlalchemy", "jinja2", "python-dotenv"]
[[fetch]]
files = [
    "data/records.db",
    "data/manoa.db",
    "data/../templates/homepage.html",
    "data/../templates/locations.html",
    "src/models.py",
    "src/utils.py",
    "src/gh.txt",
    "src/local.txt"
]