interpreter = "0.23.4"
packages = ["lxml", "jinja2", "sqlalchemy"]
[[fetch]]
files = [
    "data/manoa.db",

    "data/../templates/components/navbar.html",
    "data/../templates/components/arrests.html",
    "data/../templates/j.html",
    "data/../templates/l.html",

    "src/models.py",
    "src/utils.py",
    "src/gh.txt",
    "src/pydom.py",
]
