name: Collect Documents

#on: push
on:
  schedule:
    - cron: '0 */3 * * *' #every three hours

jobs:
  collector:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Find Records in Oahu
        run: |
          sudo apt-get install libxml2-dev libxslt-dev libyaml-dev
          pip install -r src/requirements.txt
          python src/collect.py

      - name: Commit Changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v5
